{'title': 'GCP Data Engineer', 'street': '10 Whites Row London', 'city': 'London', 'country_code': 'GB',
 'address_text': '10 Whites Row London, London', 'marker_icon': 'python', 'workplace_type': 'remote',
 'company_name': 'Senovo _ IT', 'company_url': 'http://www.senovo-it.com', 'company_size': '30',
 'experience_level': 'senior', 'latitude': '51.518276', 'longitude': '-0.074984',
 'published_at': '2023-01-09T16:00:10.635Z', 'remote_interview': True, 'open_to_hire_ukrainians': True,
 'id': 'senovo-_-it-gcp-data-engineer', 'display_offer': True,
 'employment_types': [{'type': 'b2b', 'salary': {'from': 40000, 'to': 40000, 'currency': 'pln'}}],
 'company_logo_url': 'https://bucket.justjoin.it/offers/company_logos/thumb/bdafd8a45d7515f3ac4b8d5c8075633d0f85b185.jpg?1672760703',
 'skills': [{'name': 'GCP', 'level': 4}, {'name': 'Data', 'level': 5}, {'name': 'Python', 'level': 5}], 'remote': True,
 'multilocation': [{'city': 'Kraków', 'slug': 'senovo-_-it-gcp-data-engineer-krakow', 'street': 'Centrum'},
                   {'city': 'Wrocław', 'slug': 'senovo-_-it-gcp-data-engineer-wroclaw', 'street': 'Centrum'},
                   {'city': 'Poznań', 'slug': 'senovo-_-it-gcp-data-engineer-poznan', 'street': 'Centrum'},
                   {'city': 'Gdańsk', 'slug': 'senovo-_-it-gcp-data-engineer-gdansk', 'street': 'Centrum'},
                   {'city': 'Warszawa', 'slug': 'senovo-_-it-gcp-data-engineer-warszawa', 'street': 'Centrum'},
                   {'city': 'London', 'slug': 'senovo-_-it-gcp-data-engineer', 'street': '10 Whites Row London'}],
 'way_of_apply': 'form'}
